@startuml
'https://plantuml.com/sequence-diagram

autonumber

group MainLayout

Bob -> Bob: Authentication Request
Bob --> Alice: Authentication Response
end

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml