@startuml
'https://plantuml.com/sequence-diagram

autonumber

alt MainLayout
'MainActivity -> MainLayout
MainLayout --> InletValveButton
InletValveButton --> ValveSettingDialog:[onClick state update]
group AlertDialog Group
ValveSettingDialog --> OldValveText
group MenuBox Group
OldValveText --> ExposedDropDownMenuBox
OldValveText --> ExposedDropDownMenu
group Loop : Item Count
ExposedDropDownMenu --> DropDownMenuItem
end
end
end
end
@enduml